"""change post

Revision ID: 1087196d8066
Revises: 8399055add41
Create Date: 2019-04-18 15:02:32.886175

"""

# revision identifiers, used by Alembic.
revision = '1087196d8066'
down_revision = '8399055add41'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('body_html', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'body_html')
    # ### end Alembic commands ###
