"""add confirmed

Revision ID: 7ad25ec98675
Revises: fb9446352099
Create Date: 2019-03-31 17:16:11.017263

"""

# revision identifiers, used by Alembic.
revision = '7ad25ec98675'
down_revision = 'fb9446352099'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('confirmed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'confirmed')
    # ### end Alembic commands ###
