"""fix bug

Revision ID: 9b9bb7143c00
Revises: ace11f2766d0
Create Date: 2019-04-20 14:49:33.506267

"""

# revision identifiers, used by Alembic.
revision = '9b9bb7143c00'
down_revision = 'ace11f2766d0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
